---
- name: Create a directory for VictoriaMetrics
  file:
    path: ~/victoriametric-binary  # Replace with the desired directory path
    state: directory
  tags:
    - preinstall
- name: Download VictoriaMetrics release using wget
  command: wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{victoria_version}}/victoria-metrics-amd64-{{victoria_version}}-cluster.tar.gz
  args:
    chdir: ~/victoriametric-binary  # Change the working directory for this task
  tags:
    - preinstall

- name: Extract VictoriaMetrics files
  command: tar -xvzf victoria-metrics-amd64-{{victoria_version}}-cluster.tar.gz
  args:
    chdir: ~/victoriametric-binary  # Change the working directory for this task
  tags:
    - preinstall

- name: List files in the directory
  command: ls
  args:
    chdir: ~/victoriametric-binary  # Change the working directory for this task
  tags:
    - preinstall