---

- name: Update package cache
  apt:
    update_cache: yes
  tags:
    - ha

- name: Upgrade packages
  apt:
    upgrade: dist
  tags:
    - ha

- name: Update apt cache
  apt:
    update_cache: yes
  tags: loadbalancer

- name: Install keepalived and nginx
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - keepalived
    - nginx
  tags: ha

- name: Create keepalived.conf file
  template:
    src:  keepalived.conf.j2 # Replace with the path to your template file
    dest: /etc/keepalived/keepalived.conf
    mode: '644'
  tags: ha

- name: Enable and start keepalived service
  service:
    name: keepalived
    state: started
    enabled: yes
  tags: ha

- name: Get the host IP address
  command: curl ifconfig.io
  register: host_ip
  tags:
    - ha

- name: Create NGINX configuration
  template:
    src: nginx_template.conf.j2
    dest: /etc/nginx/sites-available/victoriametrics
  notify: Reload NGINX
  tags:
    - ha

- name: Check NGINX configuration syntax
  command: nginx -t
  register: nginx_syntax
  tags:
    - ha

- name: Reload NGINX if syntax is okay
  command: systemctl reload nginx
  when: nginx_syntax.rc == 0
  tags:
    - ha