---

- name: delete node_exporter release using rm
  command: rm -rf /node_exporter-{{nodeexporter_version}}.linux-amd64.tar.gz*
  args:
    chdir: ~/prometheus_tools  # Change the working directory for this task
  tags:
    - node_exporter

#NODE_EXPORTER_VERSION="1.3.1"
- name: Download node_exporter release using wget
  command: wget https://github.com/prometheus/node_exporter/releases/download/v{{nodeexporter_version}}/node_exporter-{{nodeexporter_version}}.linux-amd64.tar.gz
  args:
    chdir: ~/prometheus_tools  # Change the working directory for this task
  tags:
    - node_exporter

- name: Extract prometheus files
  command: tar -xvzf node_exporter-{{nodeexporter_version}}.linux-amd64.tar.gz
  args:
    chdir: ~/prometheus_tools  # Change the working directory for this task
  tags:
    - node_exporter

- name: List files in the directory
  command: ls
  args:
    chdir: ~/prometheus_tools  # Change the working directory for this task
  tags:
    - node_exporter

- name: Copy node_exporter to /bin/
  command: "rsync -av ~/prometheus_tools/node_exporter-{{nodeexporter_version}}.linux-amd64/node_exporter /usr/local/bin/"
  tags:
    - node_exporter


- name: Create /var/log/node_exporter/ directory
  file:
    path: /var/log/node_exporter/
    state: directory
  tags:
    - node_exporter


- name: Create node_exporter systemd service file
  template:
    src: node_exporter.service.j2  # Use a Jinja2 template for the service file
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644  # Set appropriate permissions
  tags:
    - node_exporter

- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags:
    - node_exporter

- name: Start node_exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes
  tags:
    - node_exporter

- name: Check prometheus service status
  systemd:
    name: node_exporter
  register: node_exporter
  tags:
    - node_exporter

- name: Display node_exporter service status
  debug:
    var: node_exporter_status.stdout
  tags:
    - node_exporter